from __future__ import annotations

import argparse
import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import numpy as np
from PIL import Image

from data_adapter import discover_samples, load_label_mask, split_dataset


CLASS_NAMES = ("background", "simple", "blocky", "pipeline", "vertical", "horizontal")
PALETTE = (
    (0, 0, 0),
    (0, 200, 255),
    (255, 80, 80),
    (140, 90, 255),
    (255, 200, 0),
    (60, 220, 90),
)


def _portable_path(path: Path) -> str:
    return path.resolve().as_posix()


@dataclass(frozen=True)
class SegFormerExportConfig:
    data_root: Path = Path(r"C:\Users\26822\Downloads\data")
    out_dir: Path = Path("experiments/segformer_b1")
    train_n: int = 700
    val_n: int = 150
    test_n: int = 150
    seed: int = 42
    label_mode: str = "multiclass"
    crop_size: int = 512
    samples_per_gpu: int = 2
    workers_per_gpu: int = 2
    max_iters: int = 160000
    eval_interval: int = 16000
    python_executable: str = "python"
    pretrained: Optional[str] = None


def export_mmseg_dataset(config: SegFormerExportConfig) -> dict:
    pairs = discover_samples(config.data_root, label_mode=config.label_mode)
    train, val, test = split_dataset(pairs, config.seed, config.train_n, config.val_n, config.test_n)
    split_pairs = {"train": train, "val": val, "test": test}
    mmseg_root = config.out_dir / "mmseg"
    manifest: dict[str, object] = {
        "data_root": str(config.data_root),
        "mmseg_root": str(mmseg_root),
        "label_mode": config.label_mode,
        "classes": list(CLASS_NAMES),
        "splits": {},
    }

    for split_name, items in split_pairs.items():
        image_dir = mmseg_root / "images" / split_name
        mask_dir = mmseg_root / "masks" / split_name
        image_dir.mkdir(parents=True, exist_ok=True)
        mask_dir.mkdir(parents=True, exist_ok=True)
        records = []
        for image_path_str, mask_path_str in items:
            image_path = Path(image_path_str)
            mask_path = Path(mask_path_str)
            folder_name = image_path.parent.parent.name
            safe_stem = f"{folder_name}_{image_path.stem}"
            image_out = image_dir / f"{safe_stem}{image_path.suffix.lower()}"
            mask_out = mask_dir / f"{safe_stem}.png"

            shutil.copy2(image_path, image_out)
            mask = load_label_mask(mask_path, folder_name, num_classes=len(CLASS_NAMES), label_mode=config.label_mode)
            Image.fromarray(mask.astype(np.uint8), mode="L").save(mask_out)
            records.append({
                "image": str(image_out.relative_to(mmseg_root)),
                "mask": str(mask_out.relative_to(mmseg_root)),
                "source_image": str(image_path),
                "source_mask": str(mask_path),
            })
        manifest["splits"][split_name] = {
            "count": len(records),
            "records": records,
        }

    config.out_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = config.out_dir / "segformer_manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return {
        "mmseg_root": mmseg_root,
        "manifest_path": manifest_path,
        "manifest": manifest,
    }


def write_segformer_config(config: SegFormerExportConfig, mmseg_root: Path) -> Path:
    config_dir = config.out_dir / "configs"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "segformer_b1_6cls.py"
    classes = tuple(CLASS_NAMES)
    palette = [list(color) for color in PALETTE]
    pretrained = repr(config.pretrained) if config.pretrained else "None"
    text = f'''# Generated by segformer_tools.py
# SegFormer B1 for 6-class tunnel defect segmentation.

dataset_type = 'CustomDataset'
data_root = {_portable_path(mmseg_root)!r}
classes = {classes!r}
palette = {palette!r}
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
crop_size = ({config.crop_size}, {config.crop_size})

train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations'),
    dict(type='Resize', img_scale=(2048, 512), ratio_range=(0.5, 2.0)),
    dict(type='RandomCrop', crop_size=crop_size, cat_max_ratio=0.75),
    dict(type='RandomFlip', prob=0.5),
    dict(type='PhotoMetricDistortion'),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size=crop_size, pad_val=0, seg_pad_val=255),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_semantic_seg']),
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(2048, 512),
        flip=False,
        transforms=[
            dict(type='AlignedResize', keep_ratio=True, size_divisor=32),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ]),
]
data = dict(
    samples_per_gpu={config.samples_per_gpu},
    workers_per_gpu={config.workers_per_gpu},
    train=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/train',
        ann_dir='masks/train',
        classes=classes,
        palette=palette,
        pipeline=train_pipeline),
    val=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/val',
        ann_dir='masks/val',
        classes=classes,
        palette=palette,
        pipeline=test_pipeline),
    test=dict(
        type=dataset_type,
        data_root=data_root,
        img_dir='images/test',
        ann_dir='masks/test',
        classes=classes,
        palette=palette,
        pipeline=test_pipeline),
)

norm_cfg = dict(type='BN', requires_grad=True)
find_unused_parameters = True
model = dict(
    type='EncoderDecoder',
    pretrained={pretrained},
    backbone=dict(type='mit_b1', style='pytorch'),
    decode_head=dict(
        type='SegFormerHead',
        in_channels=[64, 128, 320, 512],
        in_index=[0, 1, 2, 3],
        feature_strides=[4, 8, 16, 32],
        channels=128,
        dropout_ratio=0.1,
        num_classes={len(CLASS_NAMES)},
        norm_cfg=norm_cfg,
        align_corners=False,
        decoder_params=dict(embed_dim=256),
        loss_decode=dict(type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0)),
    train_cfg=dict(),
    test_cfg=dict(mode='whole'),
)

optimizer = dict(
    type='AdamW', lr=0.00006, betas=(0.9, 0.999), weight_decay=0.01,
    paramwise_cfg=dict(
        custom_keys={{
            'pos_block': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.),
            'head': dict(lr_mult=10.),
        }},
    ),
)
optimizer_config = dict()
lr_config = dict(
    policy='poly', warmup='linear', warmup_iters=1500,
    warmup_ratio=1e-6, power=1.0, min_lr=0.0, by_epoch=False,
)

runner = dict(type='IterBasedRunner', max_iters={config.max_iters})
checkpoint_config = dict(by_epoch=False, interval={config.eval_interval})
evaluation = dict(interval={config.eval_interval}, metric='mIoU', save_best='mIoU')

log_config = dict(
    interval=50,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
    ],
)
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
cudnn_benchmark = True
'''
    config_path.write_text(text, encoding="utf-8")
    return config_path


def write_launchers(config: SegFormerExportConfig, segformer_config: Path, segformer_repo_root: Path) -> dict[str, Path]:
    config.out_dir.mkdir(parents=True, exist_ok=True)
    train_path = config.out_dir / "train_segformer_b1.ps1"
    test_path = config.out_dir / "test_segformer_b1.ps1"
    work_dir = config.out_dir / "runs" / "segformer_b1_6cls"
    train_path.write_text(
        "\n".join([
            "$ErrorActionPreference = 'Stop'",
            f"Set-Location {_portable_path(segformer_repo_root)!r}",
            f"& {config.python_executable!r} tools/train.py {_portable_path(segformer_config)!r} --work-dir {_portable_path(work_dir)!r} --gpus 1",
            "",
        ]),
        encoding="utf-8",
    )
    test_path.write_text(
        "\n".join([
            "$ErrorActionPreference = 'Stop'",
            "param([Parameter(Mandatory=$true)][string]$Checkpoint)",
            f"Set-Location {_portable_path(segformer_repo_root)!r}",
            f"& {config.python_executable!r} tools/test.py {_portable_path(segformer_config)!r} $Checkpoint --eval mIoU",
            "",
        ]),
        encoding="utf-8",
    )
    return {"train": train_path, "test": test_path}


def prepare_segformer(config: SegFormerExportConfig, segformer_repo_root: Path) -> dict:
    export = export_mmseg_dataset(config)
    config_path = write_segformer_config(config, export["mmseg_root"])
    launchers = write_launchers(config, config_path, segformer_repo_root)
    result = {
        "mmseg_root": str(export["mmseg_root"]),
        "manifest_path": str(export["manifest_path"]),
        "config_path": str(config_path),
        "train_launcher": str(launchers["train"]),
        "test_launcher": str(launchers["test"]),
        "split_counts": {
            split: payload["count"]
            for split, payload in export["manifest"]["splits"].items()
        },
    }
    summary_path = config.out_dir / "segformer_prepare_summary.json"
    summary_path.write_text(json.dumps(result, indent=2, ensure_ascii=False), encoding="utf-8")
    result["summary_path"] = str(summary_path)
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Prepare the 6-class tunnel dataset for SegFormer/mmseg training.")
    parser.add_argument("--data-root", type=Path, default=SegFormerExportConfig.data_root)
    parser.add_argument("--out-dir", type=Path, default=SegFormerExportConfig.out_dir)
    parser.add_argument("--segformer-repo-root", type=Path, default=Path(r"C:\Users\26822\Desktop\隧道病害检测\third_party\SegFormer-master"))
    parser.add_argument("--train-n", type=int, default=700)
    parser.add_argument("--val-n", type=int, default=150)
    parser.add_argument("--test-n", type=int, default=150)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-iters", type=int, default=160000)
    parser.add_argument("--eval-interval", type=int, default=16000)
    parser.add_argument("--python-executable", default="python")
    parser.add_argument("--pretrained", default=None, help="Optional path to a MiT-B1 pretrained .pth file.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = SegFormerExportConfig(
        data_root=args.data_root,
        out_dir=args.out_dir,
        train_n=args.train_n,
        val_n=args.val_n,
        test_n=args.test_n,
        seed=args.seed,
        max_iters=args.max_iters,
        eval_interval=args.eval_interval,
        python_executable=args.python_executable,
        pretrained=args.pretrained,
    )
    result = prepare_segformer(config, args.segformer_repo_root)
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
