from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np
from PIL import Image


MASK_SUFFIXES = [".png", ".jpg", ".jpeg", ".bmp"]
REQUIRED_MANIFEST_FIELDS = ["frame_id", "image_path", "video_time_sec"]
REQUIRED_METADATA_FIELDS = [
    "inspection_id",
    "frame_id",
    "timestamp",
    "video_time_sec",
    "image_path",
    "mileage_m",
    "mileage_text",
    "ring_id",
    "position_angle",
    "camera_id",
]
OUTPUT_FIELDS = [
    "inspection_id",
    "frame_id",
    "image_path",
    "mask_path",
    "video_time_sec",
    "timestamp",
    "mileage_m",
    "mileage_text",
    "ring_id",
    "position_angle",
    "camera_id",
    "disease_area",
    "bbox_x",
    "bbox_y",
    "bbox_w",
    "bbox_h",
    "center_x",
    "center_y",
    "mask_width",
    "mask_height",
    "disease_type",
    "risk_level",
    "feature_source",
    "feature_limit_note",
]
FEATURE_SOURCE = "mask_nonzero_pixels"
FEATURE_LIMIT_NOTE = "features are extracted from provided masks, not model inference; risk_level is rule_based_area_only"
MEDIUM_AREA_THRESHOLD = 1000
HIGH_AREA_THRESHOLD = 5000


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Extract video frame disease geometry features from provided masks.")
    parser.add_argument(
        "--frames_manifest",
        "--frames-manifest",
        dest="frames_manifest",
        type=Path,
        required=True,
        help="frames_manifest.csv generated by extract_video_frames.py.",
    )
    parser.add_argument(
        "--metadata_csv",
        "--metadata-csv",
        dest="metadata_csv",
        type=Path,
        required=True,
        help="metadata.csv generated by generate_video_frame_metadata.py.",
    )
    parser.add_argument(
        "--masks_dir",
        "--masks-dir",
        dest="masks_dir",
        type=Path,
        required=True,
        help="Folder containing masks named by frame_id.",
    )
    parser.add_argument(
        "--output_csv",
        "--output-csv",
        dest="output_csv",
        type=Path,
        required=True,
        help="Output disease feature CSV path.",
    )
    return parser.parse_args()


def read_csv_rows(path: Path, required_fields: list[str], label: str) -> list[dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(f"{label} not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"{label} is empty or missing header")
        missing = [field for field in required_fields if field not in reader.fieldnames]
        if missing:
            raise ValueError(f"{label} missing required fields: {', '.join(missing)}")
        rows = list(reader)
    if not rows:
        raise ValueError(f"{label} contains no rows")
    return rows


def index_metadata_rows(rows: list[dict[str, str]]) -> dict[str, dict[str, str]]:
    metadata_by_frame: dict[str, dict[str, str]] = {}
    for row_number, row in enumerate(rows, start=1):
        frame_id = (row.get("frame_id") or "").strip()
        if not frame_id:
            raise ValueError(f"metadata_csv row {row_number} missing frame_id")
        if frame_id in metadata_by_frame:
            raise ValueError(f"metadata_csv duplicate frame_id: {frame_id}")
        metadata_by_frame[frame_id] = row
    return metadata_by_frame


def find_mask_path(masks_dir: Path, frame_id: str) -> Path:
    for suffix in MASK_SUFFIXES:
        candidate = masks_dir / f"{frame_id}{suffix}"
        if candidate.is_file():
            return candidate
    raise FileNotFoundError(f"mask not found for frame_id: {frame_id} in {masks_dir}")


def area_to_risk_level(area: int) -> str:
    # This is only a simple display rule for Stage3A, not an engineering risk model.
    if area >= HIGH_AREA_THRESHOLD:
        return "high"
    if area >= MEDIUM_AREA_THRESHOLD:
        return "medium"
    return "low"


def extract_mask_features(mask_path: Path) -> dict[str, int | str]:
    mask_array = np.array(Image.open(mask_path).convert("L"))
    mask = mask_array > 0
    height, width = mask_array.shape[:2]
    area = int(mask.sum())
    if area == 0:
        return {
            "disease_area": 0,
            "bbox_x": -1,
            "bbox_y": -1,
            "bbox_w": -1,
            "bbox_h": -1,
            "center_x": "-1",
            "center_y": "-1",
            "mask_width": width,
            "mask_height": height,
        }

    ys, xs = np.nonzero(mask)
    x_min = int(xs.min())
    y_min = int(ys.min())
    x_max = int(xs.max())
    y_max = int(ys.max())
    return {
        "disease_area": area,
        "bbox_x": x_min,
        "bbox_y": y_min,
        "bbox_w": x_max - x_min + 1,
        "bbox_h": y_max - y_min + 1,
        "center_x": f"{float(xs.mean()):.3f}",
        "center_y": f"{float(ys.mean()):.3f}",
        "mask_width": width,
        "mask_height": height,
    }


def build_feature_rows(
    manifest_rows: list[dict[str, str]],
    metadata_by_frame: dict[str, dict[str, str]],
    masks_dir: Path,
) -> list[dict[str, str | int]]:
    if not masks_dir.is_dir():
        raise FileNotFoundError(f"masks_dir not found: {masks_dir}")

    rows: list[dict[str, str | int]] = []
    for row_number, manifest_row in enumerate(manifest_rows, start=1):
        frame_id = (manifest_row.get("frame_id") or "").strip()
        if not frame_id:
            raise ValueError(f"frames_manifest row {row_number} missing frame_id")
        metadata = metadata_by_frame.get(frame_id)
        if metadata is None:
            raise ValueError(f"metadata not found for frame_id: {frame_id}")

        mask_path = find_mask_path(masks_dir, frame_id)
        features = extract_mask_features(mask_path)
        disease_area = int(features["disease_area"])
        rows.append(
            {
                "inspection_id": metadata["inspection_id"],
                "frame_id": frame_id,
                "image_path": metadata["image_path"],
                "mask_path": mask_path.as_posix(),
                "video_time_sec": metadata["video_time_sec"],
                "timestamp": metadata["timestamp"],
                "mileage_m": metadata["mileage_m"],
                "mileage_text": metadata["mileage_text"],
                "ring_id": metadata["ring_id"],
                "position_angle": metadata["position_angle"],
                "camera_id": metadata["camera_id"],
                **features,
                "disease_type": "unknown",
                "risk_level": area_to_risk_level(disease_area),
                "feature_source": FEATURE_SOURCE,
                "feature_limit_note": FEATURE_LIMIT_NOTE,
            }
        )
    return rows


def write_feature_rows(output_csv: Path, rows: list[dict[str, str | int]]) -> None:
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    with output_csv.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def extract_video_mask_features(
    frames_manifest: Path,
    metadata_csv: Path,
    masks_dir: Path,
    output_csv: Path,
) -> list[dict[str, str | int]]:
    manifest_rows = read_csv_rows(frames_manifest, REQUIRED_MANIFEST_FIELDS, "frames_manifest")
    metadata_rows = read_csv_rows(metadata_csv, REQUIRED_METADATA_FIELDS, "metadata_csv")
    metadata_by_frame = index_metadata_rows(metadata_rows)
    rows = build_feature_rows(manifest_rows, metadata_by_frame, masks_dir)
    write_feature_rows(output_csv, rows)
    return rows


def main() -> None:
    args = parse_args()
    try:
        rows = extract_video_mask_features(
            frames_manifest=args.frames_manifest,
            metadata_csv=args.metadata_csv,
            masks_dir=args.masks_dir,
            output_csv=args.output_csv,
        )
    except Exception as exc:
        raise SystemExit(f"error: {exc}") from exc

    print("video mask feature extraction completed")
    print(f"frames_manifest: {args.frames_manifest}")
    print(f"metadata_csv: {args.metadata_csv}")
    print(f"masks_dir: {args.masks_dir}")
    print(f"output_csv: {args.output_csv}")
    print(f"feature_rows: {len(rows)}")
    print(f"feature_source: {FEATURE_SOURCE}")


if __name__ == "__main__":
    main()
