from __future__ import annotations

import argparse
import csv
from datetime import datetime, timedelta
from pathlib import Path


REQUIRED_MANIFEST_FIELDS = ["video_id", "frame_id", "video_time_sec", "image_path"]
OUTPUT_FIELDS = [
    "inspection_id",
    "frame_id",
    "timestamp",
    "video_time_sec",
    "image_path",
    "mileage_m",
    "mileage_text",
    "ring_id",
    "position_angle",
    "camera_id",
    "robot_pose",
    "metadata_source",
    "metadata_limit_note",
]
METADATA_SOURCE = "estimated_from_video_time"
METADATA_LIMIT_NOTE = "mileage and ring_id are estimated, not real robot localization"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate estimated inspection metadata from video frame manifest.")
    parser.add_argument(
        "--frames_manifest",
        "--frames-manifest",
        dest="frames_manifest",
        type=Path,
        required=True,
        help="frames_manifest.csv generated by extract_video_frames.py.",
    )
    parser.add_argument(
        "--output_csv",
        "--output-csv",
        dest="output_csv",
        type=Path,
        required=True,
        help="Output metadata CSV path.",
    )
    parser.add_argument("--inspection_id", "--inspection-id", dest="inspection_id", default=None)
    parser.add_argument("--start_timestamp", "--start-timestamp", dest="start_timestamp", default="2026-07-03T00:00:00")
    parser.add_argument("--start_mileage_m", "--start-mileage-m", dest="start_mileage_m", type=float, default=0.0)
    parser.add_argument("--robot_speed_mps", "--robot-speed-mps", dest="robot_speed_mps", type=float, default=0.0)
    parser.add_argument("--ring_length_m", "--ring-length-m", dest="ring_length_m", type=float, default=1.2)
    parser.add_argument("--camera_id", "--camera-id", dest="camera_id", default="camera_01")
    parser.add_argument("--position_angle", "--position-angle", dest="position_angle", default="unknown")
    return parser.parse_args()


def parse_start_timestamp(value: str) -> datetime:
    # Accept ISO strings from CLI and common space-separated datetime text.
    normalized = value.strip().replace(" ", "T")
    try:
        return datetime.fromisoformat(normalized)
    except ValueError as exc:
        raise ValueError(f"start_timestamp must be ISO-like datetime, got: {value}") from exc


def validate_numeric_args(start_mileage_m: float, robot_speed_mps: float, ring_length_m: float) -> None:
    if start_mileage_m < 0:
        raise ValueError("start_mileage_m must be non-negative")
    if robot_speed_mps < 0:
        raise ValueError("robot_speed_mps must be non-negative")
    if ring_length_m <= 0:
        raise ValueError("ring_length_m must be greater than 0")


def mileage_to_text(mileage_m: float) -> str:
    km = int(mileage_m // 1000)
    meters = mileage_m - km * 1000
    return f"K{km}+{meters:05.1f}"


def read_manifest(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(f"frames_manifest not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError("frames_manifest is empty or missing header")
        missing = [field for field in REQUIRED_MANIFEST_FIELDS if field not in reader.fieldnames]
        if missing:
            raise ValueError(f"frames_manifest missing required fields: {', '.join(missing)}")
        rows = list(reader)
    if not rows:
        raise ValueError("frames_manifest contains no frame rows")
    return rows


def parse_video_time(row: dict[str, str], row_number: int) -> float:
    value = row.get("video_time_sec", "")
    try:
        video_time_sec = float(value)
    except ValueError as exc:
        raise ValueError(f"row {row_number} has invalid video_time_sec: {value}") from exc
    if video_time_sec < 0:
        raise ValueError(f"row {row_number} video_time_sec must be non-negative")
    return video_time_sec


def build_metadata_rows(
    manifest_rows: list[dict[str, str]],
    inspection_id: str | None,
    start_timestamp: datetime,
    start_mileage_m: float,
    robot_speed_mps: float,
    ring_length_m: float,
    camera_id: str,
    position_angle: str,
) -> list[dict[str, str]]:
    first_video_id = (manifest_rows[0].get("video_id") or "").strip()
    resolved_inspection_id = inspection_id or first_video_id
    if not resolved_inspection_id:
        raise ValueError("inspection_id is required when manifest video_id is empty")

    rows: list[dict[str, str]] = []
    for index, row in enumerate(manifest_rows, start=1):
        frame_id = (row.get("frame_id") or "").strip()
        image_path = (row.get("image_path") or "").strip()
        if not frame_id:
            raise ValueError(f"row {index} missing frame_id")
        if not image_path:
            raise ValueError(f"row {index} missing image_path")

        video_time_sec = parse_video_time(row, index)
        timestamp = start_timestamp + timedelta(seconds=video_time_sec)
        mileage_m = start_mileage_m + robot_speed_mps * video_time_sec
        ring_id = int(mileage_m / ring_length_m)
        robot_pose = f"estimated_mileage_m={mileage_m:.3f};position_angle={position_angle}"

        rows.append(
            {
                "inspection_id": resolved_inspection_id,
                "frame_id": frame_id,
                "timestamp": timestamp.isoformat(timespec="seconds"),
                "video_time_sec": f"{video_time_sec:.6f}",
                "image_path": image_path,
                "mileage_m": f"{mileage_m:.3f}",
                "mileage_text": mileage_to_text(mileage_m),
                "ring_id": str(ring_id),
                "position_angle": position_angle,
                "camera_id": camera_id,
                "robot_pose": robot_pose,
                "metadata_source": METADATA_SOURCE,
                "metadata_limit_note": METADATA_LIMIT_NOTE,
            }
        )
    return rows


def write_metadata(path: Path, rows: list[dict[str, str]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_FIELDS)
        writer.writeheader()
        writer.writerows(rows)


def generate_video_frame_metadata(
    frames_manifest: Path,
    output_csv: Path,
    inspection_id: str | None = None,
    start_timestamp: str = "2026-07-03T00:00:00",
    start_mileage_m: float = 0.0,
    robot_speed_mps: float = 0.0,
    ring_length_m: float = 1.2,
    camera_id: str = "camera_01",
    position_angle: str = "unknown",
) -> list[dict[str, str]]:
    validate_numeric_args(start_mileage_m, robot_speed_mps, ring_length_m)
    manifest_rows = read_manifest(frames_manifest)
    rows = build_metadata_rows(
        manifest_rows=manifest_rows,
        inspection_id=inspection_id,
        start_timestamp=parse_start_timestamp(start_timestamp),
        start_mileage_m=start_mileage_m,
        robot_speed_mps=robot_speed_mps,
        ring_length_m=ring_length_m,
        camera_id=camera_id,
        position_angle=position_angle,
    )
    write_metadata(output_csv, rows)
    return rows


def main() -> None:
    args = parse_args()
    try:
        rows = generate_video_frame_metadata(
            frames_manifest=args.frames_manifest,
            output_csv=args.output_csv,
            inspection_id=args.inspection_id,
            start_timestamp=args.start_timestamp,
            start_mileage_m=args.start_mileage_m,
            robot_speed_mps=args.robot_speed_mps,
            ring_length_m=args.ring_length_m,
            camera_id=args.camera_id,
            position_angle=args.position_angle,
        )
    except Exception as exc:
        raise SystemExit(f"error: {exc}") from exc

    print("video frame metadata generation completed")
    print(f"frames_manifest: {args.frames_manifest}")
    print(f"output_csv: {args.output_csv}")
    print(f"metadata_rows: {len(rows)}")
    print(f"metadata_source: {METADATA_SOURCE}")


if __name__ == "__main__":
    main()
